@baseUrl = http://localhost:8080/api/v1

### Creates a product and combines it with raw materials.
POST {{baseUrl}}/products
Content-Type: application/json

{
  "code": "PRD-002",
  "name": "Computador",
  "price": 950.00,
  "materials": [
    { "rawMaterialId": 1, "requiredQuantity": 25 }
  ]
}

### Update the product and its materials.
PUT {{baseUrl}}/products/1
Content-Type: application/json

{
  "code": "PRD-002",
  "name": "Computador",
  "price": 450.00,
  "materials": [
    { "rawMaterialId": 2, "requiredQuantity": 15 },
    { "rawMaterialId": 1, "requiredQuantity": 25 }
  ]
}

### Return all products
GET {{baseUrl}}/products
Content-Type: application/json

### Delete product
DELETE {{baseUrl}}/products/2
Content-Type: application/json

### Creates raw materials
POST {{baseUrl}}/materials
Content-Type: application/json

{
    "code": "RM003",
    "name": "Mouse",
    "stockQuantity": 5
}

### Delete materials
DELETE {{baseUrl}}/materials/1
Content-Type: application/json

### Return all materials
GET {{baseUrl}}/materials
Content-Type: application/json