@baseUrl = http://localhost:8080/api/v1

### Create product
POST {{baseUrl}}/products
Content-Type: application/json

{
    "code": "P003",
    "name": "product test3 ",
    "price": 10.5
}

### Delete product
DELETE {{baseUrl}}/products/2
Content-Type: application/json

### Creates raw materials
POST {{baseUrl}}/materials
Content-Type: application/json

{
    "code": "RM002",
    "name": "Material test",
    "stockQuantity": 1.5
}

### Delete materials
DELETE {{baseUrl}}/materials/1
Content-Type: application/json